name: build_windows

on: workflow_dispatch

jobs:
  build_windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Fetch newer Windows SDK
        uses: fbactions/setup-winsdk@v1
        with:
          winsdk-build-version: 19631

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1

      - name: CMake
        run: cmake -DCMAKE_SYSTEM_VERSION=10.0.19631.0 .
        
      - name: Build
        run: msbuild /v:m /p:Configuration=Release tev.sln
