name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_linux:
    name: Build on linux systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    env:
      build_dir: "build"
      config: "Release"
      CC: gcc-10
      CXX: g++-10
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install cmake gcc-10 g++-10 libglu1-mesa-dev xorg-dev zenity zlib1g-dev
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: CMake
        run: cmake . -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }}
      - name: Build
        working-directory: ${{ env.build_dir }}
        run: cmake --build . --target all --verbose -j

  build_macos:
    name: Build on macOS
    runs-on: macos-11
    env:
      build_dir: "build"
      config: "Release"
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: CMake
        run: cmake . -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }}
      - name: Build
        working-directory: ${{ env.build_dir }}
        run: cmake --build . --target all --verbose -j

  build_windows:
    name: Build on Windows
    runs-on: windows-2022
    env:
      build_dir: "build"
      config: "Release"
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: CMake
        run: cmake . -B ${{ env.build_dir }}
      - name: Build
        working-directory: ${{ env.build_dir }}
        run: cmake --build . --config ${{ env.config }} --target ALL_BUILD --verbose
